language: cpp
sudo: false
compiler:
  - gcc
  - clang
before_install:
  - echo $LANG
  - echo $LC_ALL
script: mkdir build && cd build && cmake ../ && make
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - libxerces-c-dev
      - libxerces-c3.1
      - libgdal1h
      - libgdal-dev
      - cmake
      - g++-4.8
      - gcc-4.8
